import { StopDataTyp } from "@interfaces/StopDataType";

const stopsData: StopDataTyp[] = [
  {
    id: 1,
    country: "Germany",
    city: "Berlin",
    postalCode: 13353,
    title: "insta",
    openingHoursFrom: 9,
    openingHoursTo: 17,
    date: "20/11/20",
    timeFrom: 10,
    timeTo: 12,
  },
  {
    id: 2,
    country: "Germany",
    city: "Berlin",
    postalCode: 13305,
    title: "BASF",
    openingHoursFrom: 9,
    openingHoursTo: 17,
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 3,
    country: "Germany",
    city: "Berlin",
    postalCode: 10439,
    title: "DropOff GmbH",
    openingHoursFrom: 9,
    openingHoursTo: 17,
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 4,
    country: "Germany",
    city: "Berlin",
    postalCode: 10999,
    title: "Instaferight GmbH",
    openingHoursFrom: 7,
    openingHoursTo: 18,
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 5,
    country: "Germany",
    city: "Berlin",
    postalCode: 10115,
    title: "Instafreight New GmbH",
    openingHoursFrom: 8,
    openingHoursTo: 18,
    date: null,
    timeFrom: null,
    timeTo: null,
  },
];

export { stopsData };
