import { StopDataTyp } from "@interfaces/StopDataType";

const stopsData: StopDataTyp[] = [
  {
    id: 1,
    country: "Germany",
    city: "Berlin",
    postalCode: 13353,
    title: "insta",
    openingHoursFrom: "09:00",
    openingHoursTo: "17:00",
    date: "04/30/2022",
    timeFrom: "10:00",
    timeTo: "12:00",
  },
  {
    id: 2,
    country: "Germany",
    city: "Berlin",
    postalCode: 13305,
    title: "BASF",
    openingHoursFrom: "09:00",
    openingHoursTo: "17:00",
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 3,
    country: "Germany",
    city: "Berlin",
    postalCode: 10439,
    title: "DropOff GmbH",
    openingHoursFrom: "09:00",
    openingHoursTo: "17:00",
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 4,
    country: "Germany",
    city: "Berlin",
    postalCode: 10999,
    title: "Instaferight GmbH",
    openingHoursFrom: "07:00",
    openingHoursTo: "18:00",
    date: null,
    timeFrom: null,
    timeTo: null,
  },
  {
    id: 5,
    country: "Germany",
    city: "Berlin",
    postalCode: 10115,
    title: "Instafreight New GmbH",
    openingHoursFrom: "08:00",
    openingHoursTo: "18:00",
    date: null,
    timeFrom: null,
    timeTo: null,
  },
];

export { stopsData };
